server:
  port: 8080

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_zs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # Spring AI配置
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-cVZTEb3pLEKqM0gfWPz3QE9jXc8cq9Zyh0Api8rESjkITqto}
      base-url: https://api.chatanywhere.tech
      model: deepseek-reasoner
      temperature: 0.7
      max-tokens: 800
      top-p: 1.0
      presence-penalty: 0.0
      frequency-penalty: 0.0

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zs.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: your-secret-key
  expiration: 86400000 # 24小时

# 日志配置
logging:
  level:
    root: info
    com.zs: debug
  file:
    name: logs/project-zs.log
